// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHWqOm0F9nPHZI5ZLufiY5eh1wIEggtUM',
    appId: '1:776841154366:web:6fa3d8e145430b77d2266f',
    messagingSenderId: '776841154366',
    projectId: 'eventmarketplace-da08d',
    authDomain: 'eventmarketplace-da08d.firebaseapp.com',
    storageBucket: 'eventmarketplace-da08d.firebasestorage.app',
    measurementId: 'G-JGX8LNSNPM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ7I2fJQtjg20PcPigDGjRAy99RERqKYA',
    appId: '1:776841154366:android:426dafd8eb2f07ebd2266f',
    messagingSenderId: '776841154366',
    projectId: 'eventmarketplace-da08d',
    storageBucket: 'eventmarketplace-da08d.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHWqOm0F9nPHZI5ZLufiY5eh1wIEggtUM',
    appId: '1:776841154366:web:875403f22e4df85fd2266f',
    messagingSenderId: '776841154366',
    projectId: 'eventmarketplace-da08d',
    authDomain: 'eventmarketplace-da08d.firebaseapp.com',
    storageBucket: 'eventmarketplace-da08d.firebasestorage.app',
    measurementId: 'G-1HLPBRHHMF',
  );
}
